/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RootRouteImport } from './routes/root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAvailabilityRouteImport } from './routes/dashboard.availability'
import { Route as DashboardCommentsRouteImport } from './routes/dashboard.comments'
import { Route as DashboardConversationsRouteImport } from './routes/dashboard.conversations'
import { Route as DashboardInquiriesRouteImport } from './routes/dashboard.inquiries'
import { Route as DashboardStaticAnswersRouteImport } from './routes/dashboard.static-answers'
import { Route as DashboardSubscribersRouteImport } from './routes/dashboard.subscribers'
import { Route as ProjectsSlugRouteImport } from './routes/projects_.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RootRoute = RootRouteImport.update({
  id: '/root',
  path: '/root',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAvailabilityRoute = DashboardAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommentsRoute = DashboardCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConversationsRoute = DashboardConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInquiriesRoute = DashboardInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaticAnswersRoute = DashboardStaticAnswersRouteImport.update({
  id: '/static-answers',
  path: '/static-answers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscribersRoute = DashboardSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => DashboardRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects_/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/recommendations': typeof RecommendationsRoute
  '/root': typeof RootRoute
  '/skills': typeof SkillsRoute
  '/status': typeof StatusRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/comments': typeof DashboardCommentsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/dashboard/static-answers': typeof DashboardStaticAnswersRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/recommendations': typeof RecommendationsRoute
  '/root': typeof RootRoute
  '/skills': typeof SkillsRoute
  '/status': typeof StatusRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/comments': typeof DashboardCommentsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/dashboard/static-answers': typeof DashboardStaticAnswersRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/case-studies': typeof CaseStudiesRoute
  '/certifications': typeof CertificationsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/recommendations': typeof RecommendationsRoute
  '/root': typeof RootRoute
  '/skills': typeof SkillsRoute
  '/status': typeof StatusRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/dashboard/availability': typeof DashboardAvailabilityRoute
  '/dashboard/comments': typeof DashboardCommentsRoute
  '/dashboard/conversations': typeof DashboardConversationsRoute
  '/dashboard/inquiries': typeof DashboardInquiriesRoute
  '/dashboard/static-answers': typeof DashboardStaticAnswersRoute
  '/dashboard/subscribers': typeof DashboardSubscribersRoute
  '/projects_/$slug': typeof ProjectsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/case-studies'
    | '/certifications'
    | '/dashboard'
    | '/education'
    | '/experience'
    | '/projects'
    | '/recommendations'
    | '/root'
    | '/skills'
    | '/status'
    | '/api/chat'
    | '/auth/callback'
    | '/blog/$slug'
    | '/dashboard/availability'
    | '/dashboard/comments'
    | '/dashboard/conversations'
    | '/dashboard/inquiries'
    | '/dashboard/static-answers'
    | '/dashboard/subscribers'
    | '/projects/$slug'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/case-studies'
    | '/certifications'
    | '/education'
    | '/experience'
    | '/projects'
    | '/recommendations'
    | '/root'
    | '/skills'
    | '/status'
    | '/api/chat'
    | '/auth/callback'
    | '/blog/$slug'
    | '/dashboard/availability'
    | '/dashboard/comments'
    | '/dashboard/conversations'
    | '/dashboard/inquiries'
    | '/dashboard/static-answers'
    | '/dashboard/subscribers'
    | '/projects/$slug'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/case-studies'
    | '/certifications'
    | '/dashboard'
    | '/education'
    | '/experience'
    | '/projects'
    | '/recommendations'
    | '/root'
    | '/skills'
    | '/status'
    | '/api/chat'
    | '/auth/callback'
    | '/blog_/$slug'
    | '/dashboard/availability'
    | '/dashboard/comments'
    | '/dashboard/conversations'
    | '/dashboard/inquiries'
    | '/dashboard/static-answers'
    | '/dashboard/subscribers'
    | '/projects_/$slug'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CertificationsRoute: typeof CertificationsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RootRoute: typeof RootRoute
  SkillsRoute: typeof SkillsRoute
  StatusRoute: typeof StatusRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/root': {
      id: '/root'
      path: '/root'
      fullPath: '/root'
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/availability': {
      id: '/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof DashboardAvailabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/comments': {
      id: '/dashboard/comments'
      path: '/comments'
      fullPath: '/dashboard/comments'
      preLoaderRoute: typeof DashboardCommentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/conversations': {
      id: '/dashboard/conversations'
      path: '/conversations'
      fullPath: '/dashboard/conversations'
      preLoaderRoute: typeof DashboardConversationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inquiries': {
      id: '/dashboard/inquiries'
      path: '/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof DashboardInquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/static-answers': {
      id: '/dashboard/static-answers'
      path: '/static-answers'
      fullPath: '/dashboard/static-answers'
      preLoaderRoute: typeof DashboardStaticAnswersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscribers': {
      id: '/dashboard/subscribers'
      path: '/subscribers'
      fullPath: '/dashboard/subscribers'
      preLoaderRoute: typeof DashboardSubscribersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/projects_/$slug': {
      id: '/projects_/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAvailabilityRoute: typeof DashboardAvailabilityRoute
  DashboardCommentsRoute: typeof DashboardCommentsRoute
  DashboardConversationsRoute: typeof DashboardConversationsRoute
  DashboardInquiriesRoute: typeof DashboardInquiriesRoute
  DashboardStaticAnswersRoute: typeof DashboardStaticAnswersRoute
  DashboardSubscribersRoute: typeof DashboardSubscribersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAvailabilityRoute: DashboardAvailabilityRoute,
  DashboardCommentsRoute: DashboardCommentsRoute,
  DashboardConversationsRoute: DashboardConversationsRoute,
  DashboardInquiriesRoute: DashboardInquiriesRoute,
  DashboardStaticAnswersRoute: DashboardStaticAnswersRoute,
  DashboardSubscribersRoute: DashboardSubscribersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CertificationsRoute: CertificationsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRoute,
  RecommendationsRoute: RecommendationsRoute,
  RootRoute: RootRoute,
  SkillsRoute: SkillsRoute,
  StatusRoute: StatusRoute,
  ApiChatRoute: ApiChatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
